book:
    path: /book
    controller: App\Controller\BookingController::bookVisit
    defaults:
        _format: json
    methods: ['POST']

get_bookings:
    path: /bookings
    controller: App\Controller\BookingController::getBookings
    methods: ['GET']
